#!/bin/sh
set -eux

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"

EXEEXT=${YLANG_EXEEXT-}
YLANG="./build/ylang$EXEEXT"

normalize_output() {
    sed 's/\r$//' "$1" > "$1.normalized"
    mv "$1.normalized" "$1"
}

"$YLANG" --version | grep -q '2.0.0-dev'
"$YLANG" --help > build/help.out
grep -q 'ylang check' build/help.out
"$YLANG" emit-c examples/demo.yl -o build/demo-generated.c > build/emit-c.out
grep -q 'Generated by YLang v2.0.0-dev' build/demo-generated.c
if "$YLANG" > build/no-args.out 2>&1; then
    echo "FAIL: ylang without arguments should return usage error" >&2
    exit 1
else
    usage_status=$?
    [ "$usage_status" -eq 64 ]
fi
if "$YLANG" fix tests/typo-print.yl > build/fix-missing-output.out 2>&1; then
    echo "FAIL: fix worked without an explicit output path" >&2
    exit 1
fi
grep -q 'requires -o' build/fix-missing-output.out

"$YLANG" check examples/demo.yl

# run builds in a temporary directory, forwards program output, and preserves its exit status.
"$YLANG" run examples/demo.yl > build/run-demo.out
normalize_output "build/run-demo.out"
diff -u tests/expected-demo.txt build/run-demo.out
set +e
"$YLANG" run tests/run-exit.yl > build/run-exit.out 2>&1
run_exit_status=$?
set -e
[ "$run_exit_status" -eq 7 ]

"$YLANG" build examples/demo.yl -o "build/test-demo$EXEEXT" >/dev/null
"./build/test-demo$EXEEXT" > build/test-demo.out
    normalize_output "build/test-demo.out"
diff -u tests/expected-demo.txt build/test-demo.out

# Safe auto-fix: replace a common typo in code, but leave strings/comments alone.
"$YLANG" fix tests/typo-print.yl -o build/typo-print-fixed.yl > build/fix.out 2> build/fix.err
grep -q "replaced 'pritn' with 'print'" build/fix.err
grep -q 'print(age);' build/typo-print-fixed.yl
grep -q 'The literal word pritn must remain unchanged.' build/typo-print-fixed.yl
grep -q 'pritn(age) inside a comment' build/typo-print-fixed.yl
grep -q 'pritn(age);' tests/typo-print.yl
"$YLANG" check build/typo-print-fixed.yl >/dev/null
"$YLANG" build build/typo-print-fixed.yl -o "build/test-typo-print$EXEEXT" >/dev/null
"./build/test-typo-print$EXEEXT" > build/test-typo-print.out
    normalize_output "build/test-typo-print.out"
diff -u tests/expected-typo-print.txt build/test-typo-print.out

# Do not rewrite a deliberately declared function called pritn.
"$YLANG" fix tests/declared-pritn.yl -o build/declared-pritn-fixed.yl > build/declared-fix.out 2>&1
cmp tests/declared-pritn.yl build/declared-pritn-fixed.yl

"$YLANG" build examples/types.yl -o "build/test-types$EXEEXT" >/dev/null
"./build/test-types$EXEEXT" > build/test-types.out
    normalize_output "build/test-types.out"
diff -u tests/expected-types.txt build/test-types.out

"$YLANG" build tests/int-min.yl -o "build/test-int-min$EXEEXT" >/dev/null
"./build/test-int-min$EXEEXT" > build/int-min.out
normalize_output "build/int-min.out"
diff -u tests/expected-int-min.txt build/int-min.out

"$YLANG" build examples/conditions.yl -o "build/test-conditions$EXEEXT" >/dev/null
"./build/test-conditions$EXEEXT" > build/test-conditions.out
    normalize_output "build/test-conditions.out"
diff -u tests/expected-conditions.txt build/test-conditions.out

"$YLANG" check tests/branch-init.yl >/dev/null
if "$YLANG" check tests/type-error.yl > build/type-error.out 2>&1; then
    echo "FAIL: type-error.yl was accepted" >&2
    exit 1
fi
grep -q 'E2001' build/type-error.out
grep -q "Did you mean 'print(value);'" build/type-error.out
grep -q 'check failed with' build/type-error.out
if grep -q 'no executable was produced' build/type-error.out; then
    echo "FAIL: check reported a build-only message" >&2
    exit 1
fi

rm -f "build/invalid-program$EXEEXT"
if "$YLANG" build tests/type-error.yl -o "build/invalid-program$EXEEXT" > build/build-type-error.out 2>&1; then
    echo "FAIL: build accepted invalid source" >&2
    exit 1
fi
grep -q 'build failed with' build/build-type-error.out
grep -q 'no executable was produced' build/build-type-error.out
if [ -e "build/invalid-program$EXEEXT" ]; then
    echo "FAIL: invalid source produced an executable" >&2
    exit 1
fi

if "$YLANG" check tests/const-assignment.yl > build/const-assignment.out 2>&1; then
    echo "FAIL: assignment to const was accepted" >&2
    exit 1
fi
grep -q 'E2022' build/const-assignment.out
grep -q "Keep 'const' and remove this assignment" build/const-assignment.out

if "$YLANG" check tests/missing-semicolon.yl > build/missing-semicolon.out 2>&1; then
    echo "FAIL: missing semicolon was accepted" >&2
    exit 1
fi
grep -q 'E1002' build/missing-semicolon.out
grep -q "missing ';' before this token" build/missing-semicolon.out

if "$YLANG" check tests/uninitialized.yl > build/uninitialized.out 2>&1; then
    echo "FAIL: uninitialized read was accepted" >&2
    exit 1
fi
grep -q 'E2021' build/uninitialized.out

"$YLANG" build tests/div-zero.yl -o "build/test-div-zero$EXEEXT" >/dev/null
set +e
"./build/test-div-zero$EXEEXT" > build/div-zero.out 2>&1
status=$?
set -e
[ "$status" -eq 70 ]
grep -q 'integer division by zero' build/div-zero.out

"$YLANG" build tests/overflow.yl -o "build/test-overflow$EXEEXT" >/dev/null
set +e
"./build/test-overflow$EXEEXT" > build/overflow.out 2>&1
status=$?
set -e
[ "$status" -eq 70 ]
grep -q 'integer overflow in addition' build/overflow.out

if command -v clang >/dev/null 2>&1; then
    "$YLANG" build examples/demo.yl -o "build/test-demo-clang$EXEEXT" --cc clang >/dev/null
    "./build/test-demo-clang$EXEEXT" > build/test-demo-clang.out
    normalize_output "build/test-demo-clang.out"
    diff -u tests/expected-demo.txt build/test-demo-clang.out
fi


# Borrowed scalar parameters: shared borrows read; exclusive borrows update the caller.
"$YLANG" build tests/borrow-read.yl -o "build/test-borrow-read$EXEEXT" >/dev/null
"./build/test-borrow-read$EXEEXT" > build/borrow-read.out
normalize_output "build/borrow-read.out"
diff -u tests/expected-borrow-read.txt build/borrow-read.out

"$YLANG" build tests/borrow-mut.yl -o "build/test-borrow-mut$EXEEXT" >/dev/null
"./build/test-borrow-mut$EXEEXT" > build/borrow-mut.out
normalize_output "build/borrow-mut.out"
diff -u tests/expected-borrow-mut.txt build/borrow-mut.out

if "$YLANG" check tests/borrow-shared-write.yl > build/borrow-shared-write.out 2>&1; then
    echo "FAIL: shared borrow allowed mutation" >&2
    exit 1
fi
grep -q 'E2022' build/borrow-shared-write.out

if "$YLANG" check tests/borrow-mode-mismatch.yl > build/borrow-mode-mismatch.out 2>&1; then
    echo "FAIL: non-borrow argument accepted by borrowed parameter" >&2
    exit 1
fi
grep -q 'E2042' build/borrow-mode-mismatch.out

if "$YLANG" check tests/borrow-conflict.yl > build/borrow-conflict.out 2>&1; then
    echo "FAIL: overlapping mutable/shared borrow accepted" >&2
    exit 1
fi
grep -q 'E2045' build/borrow-conflict.out

if "$YLANG" check tests/borrow-nested-conflict.yl > build/borrow-nested-conflict.out 2>&1; then
    echo "FAIL: nested conflicting borrow accepted" >&2
    exit 1
fi
grep -q 'E2045' build/borrow-nested-conflict.out

if "$YLANG" check tests/borrow-global.yl > build/borrow-global.out 2>&1; then
    echo "FAIL: mutable global borrow accepted" >&2
    exit 1
fi
grep -q 'E2065' build/borrow-global.out


# YLang 2.0 preview: arrays, moves, loops, and standard input.
"$YLANG" build tests/v2-arrays.yl -o "build/test-v2-arrays$EXEEXT" >/dev/null
"./build/test-v2-arrays$EXEEXT" > build/v2-arrays.out
normalize_output "build/v2-arrays.out"
diff -u tests/expected-v2-arrays.txt build/v2-arrays.out

"$YLANG" build tests/v2-for.yl -o "build/test-v2-for$EXEEXT" >/dev/null
"./build/test-v2-for$EXEEXT" > build/v2-for.out
normalize_output "build/v2-for.out"
diff -u tests/expected-v2-for.txt build/v2-for.out

"$YLANG" build tests/v2-input.yl -o "build/test-v2-input$EXEEXT" >/dev/null
printf '27\nhello YLang\n' | "./build/test-v2-input$EXEEXT" > build/v2-input.out
normalize_output "build/v2-input.out"
diff -u tests/expected-v2-input.txt build/v2-input.out

if "$YLANG" check tests/v2-move-after-use.yl > build/v2-move-after-use.out 2>&1; then
    echo "FAIL: moved string was read again" >&2
    exit 1
fi
grep -q 'E2080' build/v2-move-after-use.out

if "$YLANG" check tests/v2-array-type-error.yl > build/v2-array-type-error.out 2>&1; then
    echo "FAIL: mixed-type array was accepted" >&2
    exit 1
fi
grep -q 'E2073' build/v2-array-type-error.out

"$YLANG" build tests/v2-bounds.yl -o "build/test-v2-bounds$EXEEXT" >/dev/null
set +e
"./build/test-v2-bounds$EXEEXT" > build/v2-bounds.out 2>&1
status=$?
set -e
[ "$status" -eq 70 ]
grep -q 'array index out of bounds' build/v2-bounds.out

# Deterministic cleanup on control-flow exits and nested function returns.
"$YLANG" emit-c tests/v2-control-cleanup.yl -o build/v2-control-cleanup.c >/dev/null
awk '/^\\/\\* YLang function:/{in_main = ($0 ~ /^\\/\\* YLang function: main \\*\\//)} in_main && /continue;/{if (previous !~ /yl_string_drop/) {print "missing cleanup before continue: " previous > "/dev/stderr"; exit 1} saw_continue=1} in_main && /break;/{if (previous !~ /yl_string_drop/) {print "missing cleanup before break: " previous > "/dev/stderr"; exit 1} saw_break=1} {previous=$0} END {if (!saw_continue || !saw_break) exit 1}' build/v2-control-cleanup.c
"$YLANG" emit-c tests/v2-return-cleanup.yl -o build/v2-return-cleanup.c >/dev/null
awk '/return yl_return_temp_/{if (previous ~ /yl_string_drop/) saw_owned_return=1} {previous=$0} END {if (!saw_owned_return) exit 1}' build/v2-return-cleanup.c
"$YLANG" build tests/v2-control-cleanup.yl -o "build/test-v2-control-cleanup$EXEEXT" >/dev/null
"./build/test-v2-control-cleanup$EXEEXT" > build/v2-control-cleanup.out
normalize_output build/v2-control-cleanup.out
diff -u tests/expected-v2-control-cleanup.txt build/v2-control-cleanup.out
"$YLANG" build tests/v2-return-cleanup.yl -o "build/test-v2-return-cleanup$EXEEXT" >/dev/null
"./build/test-v2-return-cleanup$EXEEXT" > build/v2-return-cleanup.out
normalize_output build/v2-return-cleanup.out
diff -u tests/expected-v2-return-cleanup.txt build/v2-return-cleanup.out

echo "All YLang 2.0 preview tests passed."
