#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"

./build/ylang --version | grep -q '1.0.0'
./build/ylang --help > build/help.out
grep -q 'ylang check' build/help.out
./build/ylang emit-c examples/demo.yl -o build/demo-generated.c > build/emit-c.out
grep -q 'Generated by YLang v1.0.0' build/demo-generated.c
if ./build/ylang > build/no-args.out 2>&1; then
    echo "FAIL: ylang without arguments should return usage error" >&2
    exit 1
else
    usage_status=$?
    [ "$usage_status" -eq 64 ]
fi
if ./build/ylang fix tests/typo-print.yl > build/fix-missing-output.out 2>&1; then
    echo "FAIL: fix worked without an explicit output path" >&2
    exit 1
fi
grep -q 'requires -o' build/fix-missing-output.out

# Embedded NUL bytes must not silently truncate source parsing.
printf 'function main() -> int { return 0; }\000function main() -> int { return 1; }\n' > build/embedded-nul.yl
if ./build/ylang check build/embedded-nul.yl > build/embedded-nul.out 2>&1; then
    echo "FAIL: source containing an embedded NUL byte was accepted" >&2
    exit 1
fi
grep -q 'contains a NUL byte' build/embedded-nul.out

./build/ylang check examples/demo.yl
./build/ylang build examples/demo.yl -o build/test-demo >/dev/null
./build/test-demo > build/test-demo.out
diff -u tests/expected-demo.txt build/test-demo.out

# Safe auto-fix: replace a common typo in code, but leave strings/comments alone.
./build/ylang fix tests/typo-print.yl -o build/typo-print-fixed.yl > build/fix.out 2> build/fix.err
grep -q "replaced 'pritn' with 'print'" build/fix.err
grep -q 'print(age);' build/typo-print-fixed.yl
grep -q 'The literal word pritn must remain unchanged.' build/typo-print-fixed.yl
grep -q 'pritn(age) inside a comment' build/typo-print-fixed.yl
grep -q 'pritn(age);' tests/typo-print.yl
./build/ylang check build/typo-print-fixed.yl >/dev/null
./build/ylang build build/typo-print-fixed.yl -o build/test-typo-print >/dev/null
./build/test-typo-print > build/test-typo-print.out
diff -u tests/expected-typo-print.txt build/test-typo-print.out

# Do not rewrite a deliberately declared function called pritn.
./build/ylang fix tests/declared-pritn.yl -o build/declared-pritn-fixed.yl > build/declared-fix.out 2>&1
cmp tests/declared-pritn.yl build/declared-pritn-fixed.yl

./build/ylang build examples/types.yl -o build/test-types >/dev/null
./build/test-types > build/test-types.out
diff -u tests/expected-types.txt build/test-types.out

./build/ylang build tests/int-min.yl -o build/test-int-min >/dev/null
./build/test-int-min > build/int-min.out
diff -u tests/expected-int-min.txt build/int-min.out

./build/ylang build examples/conditions.yl -o build/test-conditions >/dev/null
./build/test-conditions > build/test-conditions.out
diff -u tests/expected-conditions.txt build/test-conditions.out

./build/ylang check tests/branch-init.yl >/dev/null
if ./build/ylang check tests/type-error.yl > build/type-error.out 2>&1; then
    echo "FAIL: type-error.yl was accepted" >&2
    exit 1
fi
grep -q 'E2001' build/type-error.out
grep -q "Did you mean 'print(value);'" build/type-error.out
grep -q 'check failed with' build/type-error.out
if grep -q 'no executable was produced' build/type-error.out; then
    echo "FAIL: check reported a build-only message" >&2
    exit 1
fi

rm -f build/invalid-program
if ./build/ylang build tests/type-error.yl -o build/invalid-program > build/build-type-error.out 2>&1; then
    echo "FAIL: build accepted invalid source" >&2
    exit 1
fi
grep -q 'build failed with' build/build-type-error.out
grep -q 'no executable was produced' build/build-type-error.out
if [ -e build/invalid-program ]; then
    echo "FAIL: invalid source produced an executable" >&2
    exit 1
fi

if ./build/ylang check tests/const-assignment.yl > build/const-assignment.out 2>&1; then
    echo "FAIL: assignment to const was accepted" >&2
    exit 1
fi
grep -q 'E2022' build/const-assignment.out
grep -q "Keep 'const' and remove this assignment" build/const-assignment.out

if ./build/ylang check tests/missing-semicolon.yl > build/missing-semicolon.out 2>&1; then
    echo "FAIL: missing semicolon was accepted" >&2
    exit 1
fi
grep -q 'E1002' build/missing-semicolon.out
grep -q "missing ';' before this token" build/missing-semicolon.out

if ./build/ylang check tests/uninitialized.yl > build/uninitialized.out 2>&1; then
    echo "FAIL: uninitialized read was accepted" >&2
    exit 1
fi
grep -q 'E2021' build/uninitialized.out

./build/ylang build tests/div-zero.yl -o build/test-div-zero >/dev/null
set +e
./build/test-div-zero > build/div-zero.out 2>&1
status=$?
set -e
[ "$status" -eq 70 ]
grep -q 'integer division by zero' build/div-zero.out

./build/ylang build tests/overflow.yl -o build/test-overflow >/dev/null
set +e
./build/test-overflow > build/overflow.out 2>&1
status=$?
set -e
[ "$status" -eq 70 ]
grep -q 'integer overflow in addition' build/overflow.out

if command -v clang >/dev/null 2>&1; then
    ./build/ylang build examples/demo.yl -o build/test-demo-clang --cc clang >/dev/null
    ./build/test-demo-clang > build/test-demo-clang.out
    diff -u tests/expected-demo.txt build/test-demo-clang.out
fi


# Standard math library: native calls, namespacing, and argument type checks.
./build/ylang check examples/math.yl >/dev/null
./build/ylang build examples/math.yl -o build/test-math >/dev/null
./build/test-math > build/test-math.out
diff -u tests/expected-math.txt build/test-math.out
if ./build/ylang check tests/math-type-error.yl > build/math-type-error.out 2>&1; then
    echo "FAIL: math.sqrt accepted an int argument without an explicit conversion" >&2
    exit 1
fi
grep -q 'Math functions require float arguments' build/math-type-error.out

# Fixed-size arrays: homogeneous initialization, indexed mutation, globals, and bounds checks.
./build/ylang check examples/arrays.yl >/dev/null
./build/ylang build examples/arrays.yl -o build/test-arrays >/dev/null
./build/test-arrays > build/test-arrays.out
diff -u tests/expected-arrays.txt build/test-arrays.out
./build/ylang build tests/array-out-of-bounds.yl -o build/test-array-oob >/dev/null
if ./build/test-array-oob > build/array-oob.out 2>&1; then
    echo "FAIL: out-of-bounds array access was accepted at runtime" >&2
    exit 1
else
    array_status=$?
    [ "$array_status" -eq 70 ]
fi
grep -q 'array index out of bounds' build/array-oob.out

if ./build/ylang check tests/array-scalar-init.yl > build/array-scalar-init.out 2>&1; then
    echo "FAIL: scalar initializer for an array was accepted" >&2
    exit 1
fi
grep -q 'Array declarations require an array literal initializer' build/array-scalar-init.out
if ./build/ylang check tests/array-mixed-types.yl > build/array-mixed-types.out 2>&1; then
    echo "FAIL: mixed-type array literal was accepted" >&2
    exit 1
fi
grep -q 'All array elements must have the same type' build/array-mixed-types.out

# String standard library and stdin line input.
./build/ylang check examples/strings.yl >/dev/null
./build/ylang build examples/strings.yl -o build/test-strings >/dev/null
./build/test-strings > build/test-strings.out
diff -u tests/expected-strings.txt build/test-strings.out
if ./build/ylang check tests/string-type-error.yl > build/string-type-error.out 2>&1; then
    echo "FAIL: string.length accepted an int argument" >&2
    exit 1
fi
grep -q 'requires string arguments' build/string-type-error.out
./build/ylang check tests/read-line.yl >/dev/null
./build/ylang build tests/read-line.yl -o build/test-read-line >/dev/null
printf 'YLang\n' | ./build/test-read-line > build/read-line.out
diff -u tests/expected-read-line.txt build/read-line.out

echo "All YLang tests passed."
