#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$ROOT"

./build/ylang --version | grep -q '1.1.0'
./build/ylang --help > build/help.out
grep -q 'ylang check' build/help.out
./build/ylang check examples/type-conversions.yl >/dev/null
./build/ylang build examples/type-conversions.yl -o build/test-type-conversions >/dev/null
./build/test-type-conversions > build/type-conversions.out
diff -u tests/expected-type-conversions.txt build/type-conversions.out
if ./build/ylang check tests/invalid-to-int.yl > build/invalid-to-int.out 2>&1; then
    echo "FAIL: to_int accepted an int argument" >&2
    exit 1
fi
grep -q "to_int expects a float argument" build/invalid-to-int.out
./build/ylang emit-c examples/demo.yl -o build/demo-generated.c > build/emit-c.out
grep -q 'Generated by YLang v1.1.0' build/demo-generated.c
if ./build/ylang > build/no-args.out 2>&1; then
    echo "FAIL: ylang without arguments should return usage error" >&2
    exit 1
else
    usage_status=$?
    [ "$usage_status" -eq 64 ]
fi
if ./build/ylang fix tests/typo-print.yl > build/fix-missing-output.out 2>&1; then
    echo "FAIL: fix worked without an explicit output path" >&2
    exit 1
fi
grep -q 'requires -o' build/fix-missing-output.out

# Embedded NUL bytes must not silently truncate source parsing.
printf 'function main() -> int { return 0; }\000function main() -> int { return 1; }\n' > build/embedded-nul.yl
if ./build/ylang check build/embedded-nul.yl > build/embedded-nul.out 2>&1; then
    echo "FAIL: source containing an embedded NUL byte was accepted" >&2
    exit 1
fi
grep -q 'contains a NUL byte' build/embedded-nul.out

./build/ylang check examples/demo.yl
./build/ylang build examples/demo.yl -o build/test-demo >/dev/null
./build/test-demo > build/test-demo.out
diff -u tests/expected-demo.txt build/test-demo.out

# Safe auto-fix: replace a common typo in code, but leave strings/comments alone.
./build/ylang fix tests/typo-print.yl -o build/typo-print-fixed.yl > build/fix.out 2> build/fix.err
grep -q "replaced 'pritn' with 'print'" build/fix.err
grep -q 'print(age);' build/typo-print-fixed.yl
grep -q 'The literal word pritn must remain unchanged.' build/typo-print-fixed.yl
grep -q 'pritn(age) inside a comment' build/typo-print-fixed.yl
grep -q 'pritn(age);' tests/typo-print.yl
./build/ylang check build/typo-print-fixed.yl >/dev/null
./build/ylang build build/typo-print-fixed.yl -o build/test-typo-print >/dev/null
./build/test-typo-print > build/test-typo-print.out
diff -u tests/expected-typo-print.txt build/test-typo-print.out

# Do not rewrite a deliberately declared function called pritn.
./build/ylang fix tests/declared-pritn.yl -o build/declared-pritn-fixed.yl > build/declared-fix.out 2>&1
cmp tests/declared-pritn.yl build/declared-pritn-fixed.yl

./build/ylang build examples/types.yl -o build/test-types >/dev/null
./build/test-types > build/test-types.out
diff -u tests/expected-types.txt build/test-types.out

./build/ylang build tests/int-min.yl -o build/test-int-min >/dev/null
./build/test-int-min > build/int-min.out
diff -u tests/expected-int-min.txt build/int-min.out

./build/ylang build examples/conditions.yl -o build/test-conditions >/dev/null
./build/test-conditions > build/test-conditions.out
diff -u tests/expected-conditions.txt build/test-conditions.out

./build/ylang check tests/branch-init.yl >/dev/null
if ./build/ylang check tests/type-error.yl > build/type-error.out 2>&1; then
    echo "FAIL: type-error.yl was accepted" >&2
    exit 1
fi
grep -q 'E2001' build/type-error.out
grep -q "Did you mean 'print(value);'" build/type-error.out
grep -q 'check failed with' build/type-error.out
if grep -q 'no executable was produced' build/type-error.out; then
    echo "FAIL: check reported a build-only message" >&2
    exit 1
fi

rm -f build/invalid-program
if ./build/ylang build tests/type-error.yl -o build/invalid-program > build/build-type-error.out 2>&1; then
    echo "FAIL: build accepted invalid source" >&2
    exit 1
fi
grep -q 'build failed with' build/build-type-error.out
grep -q 'no executable was produced' build/build-type-error.out
if [ -e build/invalid-program ]; then
    echo "FAIL: invalid source produced an executable" >&2
    exit 1
fi

if ./build/ylang check tests/const-assignment.yl > build/const-assignment.out 2>&1; then
    echo "FAIL: assignment to const was accepted" >&2
    exit 1
fi
grep -q 'E2022' build/const-assignment.out
grep -q "Keep 'const' and remove this assignment" build/const-assignment.out

if ./build/ylang check tests/missing-semicolon.yl > build/missing-semicolon.out 2>&1; then
    echo "FAIL: missing semicolon was accepted" >&2
    exit 1
fi
grep -q 'E1002' build/missing-semicolon.out
grep -q "missing ';' before this token" build/missing-semicolon.out

if ./build/ylang check tests/uninitialized.yl > build/uninitialized.out 2>&1; then
    echo "FAIL: uninitialized read was accepted" >&2
    exit 1
fi
grep -q 'E2021' build/uninitialized.out

./build/ylang build tests/div-zero.yl -o build/test-div-zero >/dev/null
set +e
./build/test-div-zero > build/div-zero.out 2>&1
status=$?
set -e
[ "$status" -eq 70 ]
grep -q 'integer division by zero' build/div-zero.out

./build/ylang build tests/overflow.yl -o build/test-overflow >/dev/null
set +e
./build/test-overflow > build/overflow.out 2>&1
status=$?
set -e
[ "$status" -eq 70 ]
grep -q 'integer overflow in addition' build/overflow.out

if command -v clang >/dev/null 2>&1; then
    ./build/ylang build examples/demo.yl -o build/test-demo-clang --cc clang >/dev/null
    ./build/test-demo-clang > build/test-demo-clang.out
    diff -u tests/expected-demo.txt build/test-demo-clang.out
fi


# Standard math library: native calls, namespacing, and argument type checks.
./build/ylang check examples/math.yl >/dev/null
./build/ylang build examples/math.yl -o build/test-math >/dev/null
./build/test-math > build/test-math.out
diff -u tests/expected-math.txt build/test-math.out
if ./build/ylang check tests/math-type-error.yl > build/math-type-error.out 2>&1; then
    echo "FAIL: math.sqrt accepted an int argument without an explicit conversion" >&2
    exit 1
fi
grep -q 'Math functions require float arguments' build/math-type-error.out

# Fixed-size arrays: homogeneous initialization, indexed mutation, globals, and bounds checks.
./build/ylang check examples/arrays.yl >/dev/null
./build/ylang build examples/arrays.yl -o build/test-arrays >/dev/null
./build/test-arrays > build/test-arrays.out
diff -u tests/expected-arrays.txt build/test-arrays.out
./build/ylang build tests/array-out-of-bounds.yl -o build/test-array-oob >/dev/null
if ./build/test-array-oob > build/array-oob.out 2>&1; then
    echo "FAIL: out-of-bounds array access was accepted at runtime" >&2
    exit 1
else
    array_status=$?
    [ "$array_status" -eq 70 ]
fi
grep -q 'array index out of bounds' build/array-oob.out

if ./build/ylang check tests/array-scalar-init.yl > build/array-scalar-init.out 2>&1; then
    echo "FAIL: scalar initializer for an array was accepted" >&2
    exit 1
fi
grep -q 'Array declarations require an array literal initializer' build/array-scalar-init.out
if ./build/ylang check tests/array-mixed-types.yl > build/array-mixed-types.out 2>&1; then
    echo "FAIL: mixed-type array literal was accepted" >&2
    exit 1
fi
grep -q 'All array elements must have the same type' build/array-mixed-types.out

# Native optimization levels are selectable without changing source code.
YLANG_OPT_LEVEL=3 ./build/ylang build examples/loops.yl -o build/test-loops-o3 >/dev/null
./build/test-loops-o3 > build/loops-o3.out
diff -u tests/expected-loops.txt build/loops-o3.out
if YLANG_OPT_LEVEL=invalid ./build/ylang build examples/loops.yl -o build/invalid-opt > build/invalid-opt.out 2>&1; then
    echo "FAIL: invalid optimization level was accepted" >&2
    exit 1
fi
grep -q 'invalid YLANG_OPT_LEVEL' build/invalid-opt.out

# C-style for loops and condition-driven while loops.
./build/ylang check examples/loops.yl >/dev/null
./build/ylang build examples/loops.yl -o build/test-loops >/dev/null
./build/test-loops > build/loops.out
diff -u tests/expected-loops.txt build/loops.out
if ./build/ylang check tests/loop-condition-error.yl > build/loop-condition-error.out 2>&1; then
    echo "FAIL: while accepted a non-bool condition" >&2
    exit 1
fi
grep -q 'while condition must have type bool' build/loop-condition-error.out

# Text file I/O: writing returns a status, reading returns a string.
./build/ylang check tests/file-io.yl >/dev/null
./build/ylang build tests/file-io.yl -o build/test-file-io >/dev/null
./build/test-file-io > build/file-io.out
diff -u tests/expected-file-io.txt build/file-io.out
printf 'YLang file I/O' > build/io-expected.txt
cmp build/io-output.txt build/io-expected.txt

# String standard library: replacement is non-overlapping and handles empty needles safely.
./build/ylang check examples/string-replace.yl >/dev/null
./build/ylang build examples/string-replace.yl -o build/test-string-replace >/dev/null
./build/test-string-replace > build/string-replace.out
diff -u tests/expected-string-replace.txt build/string-replace.out

# String standard library and stdin line input.
./build/ylang check examples/strings.yl >/dev/null
./build/ylang build examples/strings.yl -o build/test-strings >/dev/null
./build/test-strings > build/test-strings.out
diff -u tests/expected-strings.txt build/test-strings.out
if ./build/ylang check tests/string-type-error.yl > build/string-type-error.out 2>&1; then
    echo "FAIL: string.length accepted an int argument" >&2
    exit 1
fi
grep -q 'requires string arguments' build/string-type-error.out
./build/ylang check tests/read-line.yl >/dev/null
./build/ylang build tests/read-line.yl -o build/test-read-line >/dev/null
printf 'YLang\n' | ./build/test-read-line > build/read-line.out
diff -u tests/expected-read-line.txt build/read-line.out



# Path utilities and safe OS image-opening integration.
./build/ylang check examples/image-preview.yl >/dev/null
./build/ylang build examples/path-utils.yl -o build/test-path-utils >/dev/null
./build/test-path-utils > build/path-utils.out
diff -u tests/expected-path-utils.txt build/path-utils.out
if ./build/ylang check tests/path-type-error.yl > build/path-type-error.out 2>&1; then
    echo "FAIL: path.exists accepted a non-string argument" >&2
    exit 1
fi
grep -q 'requires string arguments' build/path-type-error.out

# Compound assignment evaluates an indexed lvalue exactly once.
./build/ylang check tests/array-compound-side-effect.yl >/dev/null
./build/ylang build tests/array-compound-side-effect.yl -o build/test-array-compound-side-effect >/dev/null
./build/test-array-compound-side-effect > build/array-compound-side-effect.out
diff -u tests/expected-array-compound-side-effect.txt build/array-compound-side-effect.out

# Capacity-aware vectors should handle larger declaration lists without quadratic copying.
: > build/many-globals.yl
i=0
while [ "$i" -lt 1000 ]; do
    printf 'let int global_%s = %s;\n' "$i" "$i" >> build/many-globals.yl
    i=$((i + 1))
done
printf 'function main() -> int { return 0; }\n' >> build/many-globals.yl
./build/ylang check build/many-globals.yl >/dev/null

# Refuse attempts to overwrite an input file through output commands.
cat > build/same-path.yl <<'EOF'
function main() -> int {
    return 0;
}
EOF
cp build/same-path.yl build/same-path.before
if ./build/ylang emit-c build/same-path.yl -o build/same-path.yl > build/same-path-emit.out 2>&1; then
    echo "FAIL: emit-c overwrote its input file" >&2
    exit 1
fi
cmp build/same-path.yl build/same-path.before
if ./build/ylang fix build/same-path.yl -o build/same-path.yl > build/same-path-fix.out 2>&1; then
    echo "FAIL: fix overwrote its input file" >&2
    exit 1
fi
cmp build/same-path.yl build/same-path.before

# Array parameters pass a checked pointer and length; length() works in callers and callees.
./build/ylang check examples/array-functions.yl >/dev/null
./build/ylang build examples/array-functions.yl -o build/test-array-functions >/dev/null
./build/test-array-functions > build/array-functions.out
diff -u tests/expected-array-functions.txt build/array-functions.out
if ./build/ylang check tests/array-param-type-error.yl > build/array-param-type-error.out 2>&1; then
    echo "FAIL: scalar passed to array parameter" >&2
    exit 1
fi
grep -q 'This parameter expects an array argument' build/array-param-type-error.out

# Numeric literal forms and multiline comments.
cat > build/literals-comments.yl <<'EOF'
/* Block comments may
   span multiple lines. */
function main() -> int {
    let int hex = 0xFF;
    let float scientific = 1e3;
    let float tiny = 2.5e-4;
    print(hex, scientific, tiny);
    return 0;
}
EOF
./build/ylang check build/literals-comments.yl >/dev/null
./build/ylang build build/literals-comments.yl -o build/test-literals-comments >/dev/null
./build/test-literals-comments > build/literals-comments.out
grep -q '255 1000 0.00025' build/literals-comments.out
cat > build/unterminated-comment.yl <<'EOF'
function main() -> int {
    /* never closed
    return 0;
}
EOF
if ./build/ylang check build/unterminated-comment.yl > build/unterminated-comment.out 2>&1; then
    echo "FAIL: unterminated block comment was accepted" >&2
    exit 1
fi
grep -q 'Unterminated block comment' build/unterminated-comment.out

# Compound addition and postfix increment.
cat > build/compound-operators.yl <<'EOF'
function main() -> int {
    let int count = 2;
    count += 3;
    count++;
    print(count);
    let float ratio = 1.5;
    ratio += 0.5;
    print(ratio);
    return 0;
}
EOF
./build/ylang check build/compound-operators.yl >/dev/null
./build/ylang build build/compound-operators.yl -o build/test-compound-operators >/dev/null
./build/test-compound-operators > build/compound-operators.out
grep -q '^6$' build/compound-operators.out
grep -q '^2$' build/compound-operators.out

echo "All YLang tests passed."
